import { mkdir, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { stringify } from "yaml"
import { ERROR_MESSAGE } from "../constants/error"
import { LOG_MESSAGE } from "../constants/log"
import type { YamlOutput } from "../types/output"
import type { CollectPattern } from "../types/pattern"

const APIS_ROOT = resolve(import.meta.dirname, "../../../../apis")

const YAML_HEADER = [
    "# Auto-generated by apps/try collector",
    "# Re-run `npm run collect` to regenerate",
    ""
].join("\n")

export async function serializeToYaml(
    pattern: CollectPattern,
    request_body: Record<string, unknown> | null,
    response_body: Record<string, unknown> | null,
    sdk_version: string,
    provider_version: string
): Promise<void> {
    const output: YamlOutput = {
        schema: {
            id: pattern.id,
            description: pattern.description,
            category: pattern.category,
            method: pattern.method,
            model_id: pattern.model_id,
            collected_at: new Date().toISOString(),
            sdk_version,
            provider_version
        },
        request: request_body ?? {},
        response: response_body ?? {}
    }

    const yaml_content =
        YAML_HEADER +
        stringify(output, {
            lineWidth: 0,
            defaultStringType: "QUOTE_DOUBLE",
            defaultKeyType: "PLAIN"
        })

    const file_path = resolve(APIS_ROOT, `${pattern.id}.yaml`)
    const directory = dirname(file_path)

    try {
        await mkdir(directory, { recursive: true })
    } catch {
        throw new Error(`${ERROR_MESSAGE.COLLECTOR_DIRECTORY_CREATION_FAILED}: ${directory}`)
    }

    try {
        await writeFile(file_path, yaml_content, "utf-8")
    } catch {
        throw new Error(`${ERROR_MESSAGE.COLLECTOR_FILE_WRITE_FAILED}: ${file_path}`)
    }

    console.log(`  ${LOG_MESSAGE.COLLECTOR_WRITE_YAML_SUCCESS}: ${file_path}`)
}
