export const LOG_MESSAGE = {
    COLLECTOR_START: "収集を開始します",
    COLLECTOR_PATTERN_START: "パターン実行中",
    COLLECTOR_PATTERN_SUCCESS: "パターン完了",
    COLLECTOR_PATTERN_FAILED: "パターン失敗",
    COLLECTOR_WRITE_YAML: "YAML書き出し中",
    COLLECTOR_WRITE_YAML_SUCCESS: "YAML書き出し完了",
    COLLECTOR_SUMMARY_HEADER: "===== 収集サマリー =====",
    COLLECTOR_SUMMARY_TOTAL: "合計",
    COLLECTOR_SUMMARY_SUCCESS: "成功",
    COLLECTOR_SUMMARY_FAILED: "失敗",
    COLLECTOR_SUMMARY_DURATION: "所要時間",
    COLLECTOR_COMPLETE: "収集が完了しました",
    COLLECTOR_RATE_LIMIT_WAIT: "レートリミット対策: 1秒待機中",
    COLLECTOR_FAILED_PATTERNS_HEADER: "失敗したパターン:"
} as const
